# Generated by Django 3.1.7 on 2021-03-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_invoicecode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='invoiceCode',
            new_name='invoice_code',
        ),
    ]
