# Generated by Django 3.1.7 on 2021-03-12 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_gross', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('price_vat', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('sales_date', models.DateTimeField(null=True)),
                ('invoice_date', models.DateTimeField(null=True)),
                ('payment_date', models.DateTimeField(null=True)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('invoice_nr', models.CharField(max_length=128, null=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_gross', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('price_vat', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('vat_rate', models.IntegerField(null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16, null=True)),
                ('total_price_gross', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('total_price_net', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('total_price_vat', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoices.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
        ),
    ]
