# Generated by Django 3.1.7 on 2021-03-15 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20210315_2159'),
        ('invoices', '0006_invoicerecord_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicerecord',
            name='place',
        ),
        migrations.AddField(
            model_name='invoice',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='places.place', verbose_name='Miejsce sprzedaży'),
        ),
    ]
