# Generated by Django 3.1.7 on 2021-03-18 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210315_2159'),
        ('invoices', '0007_auto_20210315_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerecord',
            name='price_gross',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Cena brutto'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='price_net',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Cena netto'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=16, null=True, verbose_name='Ilość'),
        ),
    ]
