# Generated by Django 3.1.7 on 2021-03-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_regon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=64, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=64, null=True, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Nazwa Klienta'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nip',
            field=models.CharField(max_length=30, null=True, verbose_name='NIP'),
        ),
    ]
