# Generated by Django 3.1.7 on 2021-03-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_stock',
            field=models.DecimalField(decimal_places=3, max_digits=16, null=True),
        ),
    ]
