# Generated by Django 3.1.7 on 2021-03-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_quantity_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Koszt'),
        ),
        migrations.AddField(
            model_name='product',
            name='gain',
            field=models.DecimalField(decimal_places=0, max_digits=16, null=True, verbose_name='Marża'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Czy jest aktywny?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_gross',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Cena Brutto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_net',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Cena Netto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_vat',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Wartość VAT'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_stock',
            field=models.DecimalField(decimal_places=3, max_digits=16, null=True, verbose_name='Stan magazynowy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.IntegerField(null=True, verbose_name='Stawka VAT'),
        ),
    ]
