# Generated by Django 3.1.7 on 2021-03-13 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210313_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.vatrate', verbose_name='Stawka VAT'),
        ),
    ]
