# Generated by Django 3.1.7 on 2021-03-15 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210313_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gain',
            field=models.IntegerField(null=True, verbose_name='Marża [%]'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Czy jest dostepny?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.vatrate', verbose_name='Stawka VAT [%]'),
        ),
    ]
